
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7" # SO
  config.vm.hostname = "control-node" #nome da Maquina Virtual
  config.vm.network "private_network", ip:"192.168.1.2" #nome da rede intera q vai disponível no ambiente do virtualbox
  config.vm.synced_folder ".", "/vagrant", type: "nfs" #grava remotamente o dado em um disco q n é da própria máquina
  config.vm.provision "shell", path: "provision.sh"
end
