Vagrant.configure("2") do |config|
    config.vm.box = "centos/7" # SO
    config.vm.hostname = "app01" #nome da Maquina Virtual
    config.vm.network "private_network", ip:"192.168.1.4" #nome da rede intera q vai disponível no ambiente do virtualbox
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.provision "shell", path: "provision.sh"
  end
  